SET standard_conforming_strings = OFF;
BEGIN;
CREATE TABLE "public"."site_acess_points" (    "fid" SERIAL,    CONSTRAINT "site_acess_points_pk" PRIMARY KEY ("fid") );
SELECT AddGeometryColumn('public','site_acess_points','geom',27700,'POINT',2);
CREATE INDEX "site_acess_points_geom_geom_idx" ON "public"."site_acess_points" USING GIST ("geom");
COMMIT;
BEGIN;
CREATE TABLE "public"."OSGR" (    "fid" SERIAL,    CONSTRAINT "OSGR_pk" PRIMARY KEY ("fid") );
SELECT AddGeometryColumn('public','OSGR','geom',27700,'POLYGON',2);
CREATE INDEX "OSGR_geom_geom_idx" ON "public"."OSGR" USING GIST ("geom");
ALTER TABLE "public"."OSGR" ADD COLUMN "GridType" VARCHAR(22);
ALTER TABLE "public"."OSGR" ADD COLUMN "GridRef" VARCHAR(12);
COMMIT;
BEGIN;
CREATE TABLE "public"."cell_05_05_meters" (    "fid" SERIAL,    CONSTRAINT "cell_05_05_meters_pk" PRIMARY KEY ("fid") );
SELECT AddGeometryColumn('public','cell_05_05_meters','geometry',27700,'POINT',2);
CREATE INDEX "cell_05_05_meters_geometry_geom_idx" ON "public"."cell_05_05_meters" USING GIST ("geometry");
ALTER TABLE "public"."cell_05_05_meters" ADD COLUMN "local_frecuency" BOOLEAN;
ALTER TABLE "public"."cell_05_05_meters" ADD COLUMN "vegetation_height" FLOAT8;
ALTER TABLE "public"."cell_05_05_meters" ADD COLUMN "trampling" BOOLEAN;
ALTER TABLE "public"."cell_05_05_meters" ADD COLUMN "cell_id" INTEGER;
ALTER TABLE "public"."cell_05_05_meters" ADD COLUMN "cuadrat_id" INTEGER;
ALTER TABLE "public"."cell_05_05_meters" ADD COLUMN "list_of_species_js" JSON;
ALTER TABLE "public"."cell_05_05_meters" ADD COLUMN "x_coordinate" FLOAT8;
ALTER TABLE "public"."cell_05_05_meters" ADD COLUMN "y_coordinate" FLOAT8;
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000D9A2328ECA461241547907493CA42C41', 1, 'f', NULL, 'f', NULL, NULL, '[
    "adasd",
    "asdasd",
    "afaf",
    "adsd"
]
', 299442.638865036, 938526.142635147);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00000C0D7E1EE74212412EEE432EDDA62C41', 2, 'f', NULL, 'f', NULL, NULL, '[
    "",
    "aaa",
    "hello"
]
', 299193.779777721, 938862.590362018);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000000000004030124142214E45A27B2C41', 3, NULL, NULL, NULL, NULL, NULL, NULL, 298000, 933329.135361709);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00006CE48C1B13331241243745C45A7F2C41', 4, NULL, NULL, NULL, NULL, NULL, NULL, 298180.776904649, 933805.383340572);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00007111AD4A29371241474E6E74B87F2C41', 5, NULL, NULL, NULL, NULL, NULL, NULL, 298442.322925828, 933852.227404066);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000F53DB9FF963C124113AC4466D47D2C41', 6, NULL, NULL, NULL, NULL, NULL, NULL, 298789.74973008, 933610.199742677);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00006F0F5D62873C1241BADB4D16DF7A2C41', 7, NULL, NULL, NULL, NULL, NULL, NULL, 298785.846058122, 933231.543562762);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000952A26E3283212416A66BF18677D2C41', 8, NULL, NULL, NULL, NULL, NULL, NULL, 298122.221825281, 933555.548335267);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000022891A8C412E1241243745C45A7F2C41', 9, 'f', NULL, NULL, NULL, NULL, NULL, 297872.386819976, 933805.383340572);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000363FEB303C391241884FA0A55D7C2C41', 10, NULL, NULL, NULL, NULL, NULL, NULL, 298575.047772396, 933422.823488698);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000D529082C2C3412417BF1BF76ED7E2C41', 11, NULL, NULL, NULL, NULL, NULL, NULL, 298251.042999891, 933750.731933161);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000BE6F97B6ED3312411F09FDA0F37D2C41', 12, NULL, NULL, NULL, NULL, NULL, NULL, 298235.428312059, 933625.814430509);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00007D6F8D7999341241F3ABBF472A7E2C41', 13, NULL, NULL, NULL, NULL, NULL, NULL, 298278.368703596, 933653.140134214);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000070108556D83912418437D41F597E2C41', 14, NULL, NULL, NULL, NULL, NULL, NULL, 298614.084491975, 933676.562165961);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000047CAEB8EC23A1241F0941BB6767D2C41', 15, NULL, NULL, NULL, NULL, NULL, NULL, 298672.639571343, 933563.355679182);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00009A5746123F3612416B67E70CB87A2C41', 16, NULL, NULL, NULL, NULL, NULL, NULL, 298383.767846459, 933212.025202972);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000027B63ABB57321241A321DDA0A07A2C41', 17, NULL, NULL, NULL, NULL, NULL, NULL, 298133.932841154, 933200.314187099);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00007111AD4A29371241474E6E74B87F2C41', 18, NULL, NULL, NULL, NULL, NULL, NULL, 298442.322925828, 933852.227404066);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000064B3CC1BB9391241E11F97F5527F2C41', 19, NULL, NULL, NULL, NULL, NULL, NULL, 298606.277148059, 933801.479668614);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000047CAEB8EC23A1241F0941BB6767D2C41', 20, NULL, NULL, NULL, NULL, NULL, NULL, 298672.639571343, 933563.355679182);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000374013258D36124193AC58E07C7C2C41', 21, NULL, NULL, NULL, NULL, NULL, NULL, 298403.286206249, 933438.43817653);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00003213F3F576321241D0949697CC7D2C41', 22, NULL, NULL, NULL, NULL, NULL, NULL, 298141.74018507, 933606.296070719);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000F84031DC89341241B5C2599C897F2C41', 23, NULL, NULL, NULL, NULL, NULL, NULL, 298274.465031638, 933828.805372319);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00007D6F8D7999341241F3ABBF472A7E2C41', 24, NULL, NULL, NULL, NULL, NULL, NULL, 298278.368703596, 933653.140134214);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000025B4EAD2B5371241B9DA25228E7D2C41', 25, NULL, NULL, NULL, NULL, NULL, NULL, 298477.455973449, 933575.066695056);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00003A6C0B60523D1241022144084E7C2C41', 26, NULL, NULL, NULL, NULL, NULL, NULL, 298836.593793574, 933415.016144783);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00009A5746123F3612416B67E70CB87A2C41', 27, NULL, NULL, NULL, NULL, NULL, NULL, 298383.767846459, 933212.025202972);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00005429F4B183351241D6C306AF847C2C41', 28, NULL, NULL, NULL, NULL, NULL, NULL, 298336.923782964, 933442.341848488);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000CDF8472CD23A12412D7D596DC67E2C41', 29, NULL, NULL, NULL, NULL, NULL, NULL, 298676.543243301, 933731.213573372);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00008CF83DEF7D3B1241F9DA2F5FE27C2C41', 30, NULL, NULL, NULL, NULL, NULL, NULL, 298719.483634838, 933489.185911982);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000FC6D510BA03812419195B44EC97B2C41', 31, NULL, NULL, NULL, NULL, NULL, NULL, 298536.011052817, 933348.653721498);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00004FFBAB8E1C341241BCF2F1A7927B2C41', 32, NULL, NULL, NULL, NULL, NULL, NULL, 298247.139327933, 933321.328017793);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00006CE48C1B13331241243745C45A7F2C41', 33, NULL, NULL, NULL, NULL, NULL, NULL, 298180.776904649, 933805.383340572);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000374013258D36124193AC58E07C7C2C41', 34, NULL, NULL, NULL, NULL, NULL, NULL, 298403.286206249, 933438.43817653);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000025B4EAD2B5371241B9DA25228E7D2C41', 35, NULL, NULL, NULL, NULL, NULL, NULL, 298477.455973449, 933575.066695056);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00009F858E35A63712417094073CCE7E2C41', 36, NULL, NULL, NULL, NULL, NULL, NULL, 298473.552301491, 933735.11724533);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000BE6F97B6ED3312411F09FDA0F37D2C41', 37, NULL, NULL, NULL, NULL, NULL, NULL, 298235.428312059, 933625.814430509);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000BE6F97B6ED3312411F09FDA0F37D2C41', 38, NULL, NULL, NULL, NULL, NULL, NULL, 298235.428312059, 933625.814430509);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000C29CB7E503381241A5388132547B2C41', 39, NULL, NULL, NULL, NULL, NULL, NULL, 298496.974333238, 933290.09864213);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000363FEB303C391241884FA0A55D7C2C41', 40, NULL, NULL, NULL, NULL, NULL, NULL, 298575.047772396, 933422.823488698);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000070108556D83912418437D41F597E2C41', 41, NULL, NULL, NULL, NULL, NULL, NULL, 298614.084491975, 933676.562165961);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00006CE48C1B13331241243745C45A7F2C41', 42, NULL, NULL, NULL, NULL, NULL, NULL, 298180.776904649, 933805.383340572);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000839DD59C00361241E11F97F5527F2C41', 43, NULL, NULL, NULL, NULL, NULL, '[
    "mnmnm",
    "ghhgh",
    "dfdfdf",
    "asdasd",
    "adad"
]
', 298368.153158628, 933801.479668614);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C00009F858E35A63712417094073CCE7E2C41', 44, NULL, NULL, NULL, NULL, NULL, NULL, 298473.552301491, 933735.11724533);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000D428E037DB36124199DAA003E47D2C41', 45, NULL, NULL, NULL, NULL, NULL, NULL, 298422.804566038, 933618.007086593);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000026B512C706351241C437DE5CAD7D2C41', 46, NULL, NULL, NULL, NULL, NULL, '[
]
', 298305.694407301, 933590.681382888);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C0000FE6FA1F341331241B9DA25228E7D2C41', 47, NULL, NULL, NULL, NULL, NULL, NULL, 298192.487920523, 933575.066695056);
INSERT INTO "public"."cell_05_05_meters" ("geometry" , "fid" , "local_frecuency", "vegetation_height", "trampling", "cell_id", "cuadrat_id", "list_of_species_js", "x_coordinate", "y_coordinate") VALUES ('0101000020346C000038413B19DE331241ED7D7724C37C2C41', 48, NULL, NULL, NULL, NULL, NULL, '[
]
', 298231.524640101, 933473.571224151);
COMMIT;
BEGIN;
CREATE TABLE "public"."quadrats" (    "fid" SERIAL,    CONSTRAINT "quadrats_pk" PRIMARY KEY ("fid") );
SELECT AddGeometryColumn('public','quadrats','geom',27700,'POINT',2);
CREATE INDEX "quadrats_geom_geom_idx" ON "public"."quadrats" USING GIST ("geom");
ALTER TABLE "public"."quadrats" ADD COLUMN "plot_id" VARCHAR(10);
ALTER TABLE "public"."quadrats" ADD COLUMN "x_coordinate" FLOAT8;
ALTER TABLE "public"."quadrats" ADD COLUMN "y_coordinate" FLOAT8;
ALTER TABLE "public"."quadrats" ADD COLUMN "altitude" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "aspect" VARCHAR(10);
ALTER TABLE "public"."quadrats" ADD COLUMN "slope" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "browsing" VARCHAR(20);
ALTER TABLE "public"."quadrats" ADD COLUMN "date" timestamp with time zone;
ALTER TABLE "public"."quadrats" ADD COLUMN "disturbance" VARCHAR(100);
ALTER TABLE "public"."quadrats" ADD COLUMN "bare_ground_cover" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "bare_rock_cover" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "litter_cover" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "open_water_cover" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "tree_cover" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "dung_rabbit" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "dung_cattle" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "dung_deer" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "dung_mountain_hare" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "dung_sheep" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "dung_others" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "dung_comments" VARCHAR(50);
ALTER TABLE "public"."quadrats" ADD COLUMN "microtopography_cover_A1" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "microtopography_cover_A2" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "microtopography_cover_A3" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "microtopography_cover_A4" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "microtopography_cover_T1" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "microtopography_cover_T2" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "microtopography_cover_T3" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "microtopography_cover_T4" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "microtopography_cover_T5" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "OSGRID_field" VARCHAR(20);
ALTER TABLE "public"."quadrats" ADD COLUMN "quadrat_id" VARCHAR(20);
ALTER TABLE "public"."quadrats" ADD COLUMN "x_coordinate_field" FLOAT8;
ALTER TABLE "public"."quadrats" ADD COLUMN "y_coordinate_field" FLOAT8;
ALTER TABLE "public"."quadrats" ADD COLUMN "type" VARCHAR(50);
ALTER TABLE "public"."quadrats" ADD COLUMN "sample_zone_id" INTEGER;
ALTER TABLE "public"."quadrats" ADD COLUMN "stratus_type" VARCHAR(50);
ALTER TABLE "public"."quadrats" ADD COLUMN "peat_depth" FLOAT8;
COMMIT;
BEGIN;
CREATE TABLE "public"."plots" (    "fid" SERIAL,    CONSTRAINT "plots_pk" PRIMARY KEY ("fid") );
SELECT AddGeometryColumn('public','plots','geom',27700,'MULTIPOLYGON',2);
CREATE INDEX "plots_geom_geom_idx" ON "public"."plots" USING GIST ("geom");
ALTER TABLE "public"."plots" ADD COLUMN "plot_id" VARCHAR(20);
ALTER TABLE "public"."plots" ADD COLUMN "type" VARCHAR(50);
ALTER TABLE "public"."plots" ADD COLUMN "sample_zone_id" INTEGER;
COMMIT;
BEGIN;
CREATE TABLE "public"."sample_zone" (    "fid" SERIAL,    CONSTRAINT "sample_zone_pk" PRIMARY KEY ("fid") );
SELECT AddGeometryColumn('public','sample_zone','geometry',27700,'MULTIPOLYGON',2);
CREATE INDEX "sample_zone_geometry_geom_idx" ON "public"."sample_zone" USING GIST ("geometry");
ALTER TABLE "public"."sample_zone" ADD COLUMN "type" VARCHAR(50);
ALTER TABLE "public"."sample_zone" ADD COLUMN "sample_zone_id" INTEGER;
COMMIT;
BEGIN;
CREATE TABLE "public"."target_stratus" (    "fid" SERIAL,    CONSTRAINT "target_stratus_pk" PRIMARY KEY ("fid") );
SELECT AddGeometryColumn('public','target_stratus','geometry',27700,'MULTIPOLYGON',2);
CREATE INDEX "target_stratus_geometry_geom_idx" ON "public"."target_stratus" USING GIST ("geometry");
ALTER TABLE "public"."target_stratus" ADD COLUMN "target_id" INTEGER;
ALTER TABLE "public"."target_stratus" ADD COLUMN "plot_id" INTEGER;
ALTER TABLE "public"."target_stratus" ADD COLUMN "type" VARCHAR(50);
ALTER TABLE "public"."target_stratus" ADD COLUMN "sample_zone_id" INTEGER;
COMMIT;
BEGIN;
CREATE TABLE "public"."background_stratus" (    "fid" SERIAL,    CONSTRAINT "background_stratus_pk" PRIMARY KEY ("fid") );
SELECT AddGeometryColumn('public','background_stratus','geometry',27700,'MULTIPOLYGON',2);
CREATE INDEX "background_stratus_geometry_geom_idx" ON "public"."background_stratus" USING GIST ("geometry");
ALTER TABLE "public"."background_stratus" ADD COLUMN "background_stratus_id" INTEGER;
ALTER TABLE "public"."background_stratus" ADD COLUMN "plot_id" INTEGER;
ALTER TABLE "public"."background_stratus" ADD COLUMN "type" VARCHAR(50);
ALTER TABLE "public"."background_stratus" ADD COLUMN "sample_zone_id" INTEGER;
COMMIT;
BEGIN;
CREATE TABLE "public"."lu_land_management" (    "fid" SERIAL,    CONSTRAINT "lu_land_management_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."lu_land_management" ADD COLUMN "land_management" VARCHAR;
INSERT INTO "public"."lu_land_management" ("fid" , "land_management") VALUES (1, 'Domestic peat extraction');
INSERT INTO "public"."lu_land_management" ("fid" , "land_management") VALUES (2, 'Commercial peat extraction');
INSERT INTO "public"."lu_land_management" ("fid" , "land_management") VALUES (3, 'Rough grazing-sheep');
INSERT INTO "public"."lu_land_management" ("fid" , "land_management") VALUES (4, 'Rough grazing-cattle');
INSERT INTO "public"."lu_land_management" ("fid" , "land_management") VALUES (5, 'Improved grassland');
INSERT INTO "public"."lu_land_management" ("fid" , "land_management") VALUES (6, 'Deer management');
INSERT INTO "public"."lu_land_management" ("fid" , "land_management") VALUES (7, 'Grouse management');
INSERT INTO "public"."lu_land_management" ("fid" , "land_management") VALUES (8, 'Forestry');
INSERT INTO "public"."lu_land_management" ("fid" , "land_management") VALUES (9, 'Nature conservation');
INSERT INTO "public"."lu_land_management" ("fid" , "land_management") VALUES (10, 'Other');
COMMIT;
BEGIN;
CREATE TABLE "public"."lu_pre_restoration_condition_cat" (    "fid" SERIAL,    CONSTRAINT "lu_pre_restoration_condition_cat_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."lu_pre_restoration_condition_cat" ADD COLUMN "pre_restoration_cat" VARCHAR;
INSERT INTO "public"."lu_pre_restoration_condition_cat" ("fid" , "pre_restoration_cat") VALUES (1, 'Actively eroding ');
INSERT INTO "public"."lu_pre_restoration_condition_cat" ("fid" , "pre_restoration_cat") VALUES (2, 'Drained blanket bog');
INSERT INTO "public"."lu_pre_restoration_condition_cat" ("fid" , "pre_restoration_cat") VALUES (3, 'Drained raised bog');
INSERT INTO "public"."lu_pre_restoration_condition_cat" ("fid" , "pre_restoration_cat") VALUES (4, 'Forestry on bog�');
COMMIT;
BEGIN;
CREATE TABLE "public"."lu_vegetation_species" (    "fid" SERIAL,    CONSTRAINT "lu_vegetation_species_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."lu_vegetation_species" ADD COLUMN "veg_sp" VARCHAR;
ALTER TABLE "public"."lu_vegetation_species" ADD COLUMN "genus" VARCHAR(20);
ALTER TABLE "public"."lu_vegetation_species" ADD COLUMN "specific" VARCHAR(2);
ALTER TABLE "public"."lu_vegetation_species" ADD COLUMN "key" VARCHAR(4);
ALTER TABLE "public"."lu_vegetation_species" ADD COLUMN "dict" JSON;
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (1, 'Agrostis_capillaris', 'AG', 'CA', 'AGCA', '{
}
');
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (2, 'Agrostis_stolonifera', 'AG', 'ST', 'AGST', '{
}
');
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (3, 'Agrostis_vinealis', 'AG', 'VI', 'AGVI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (4, 'Algae_species', 'AL', 'SP', 'ALSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (5, 'Andromeda_polifolia', 'AN', 'PO', 'ANPO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (6, 'Anthoxanthum_odoratum', 'AN', 'OD', 'ANOD', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (7, 'Aulacomnium_palustre', 'AU', 'PA', 'AUPA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (8, 'Betula_pendula', 'BE', 'PE', 'BEPE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (9, 'Betula_pendula_canopy', 'BE', 'PE', 'BEPE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (10, 'Betula_pubescens', 'BE', 'PU', 'BEPU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (11, 'Betula_pubescens_canopy', 'BE', 'PU', 'BEPU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (12, 'Betula_pubescens_sapling', 'BE', 'PU', 'BEPU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (13, 'Betula_pubescens_seedling', 'BE', 'PU', 'BEPU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (14, 'Betula_species', 'BE', 'SP', 'BESP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (15, 'Blechnum_spicant', 'BL', 'SP', 'BLSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (16, 'Brachythecium_rutabulum', 'BR', 'RU', 'BRRU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (17, 'Brachythecium_species', 'BR', 'SP', 'BRSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (18, 'Calliergon_cuspidatum', 'CA', 'CU', 'CACU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (19, 'Calluna_vulgaris', 'CA', 'VU', 'CAVU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (20, 'Calluna_vulgaris_dead', 'CA', 'VU', 'CAVU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (21, 'Calypogeia_species', 'CA', 'SP', 'CASP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (22, 'Campylopus_atrovirens', 'CA', 'AT', 'CAAT', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (23, 'Campylopus_flexuosus', 'CA', 'FL', 'CAFL', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (24, 'Campylopus_introflexus', 'CA', 'IN', 'CAIN', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (25, 'Campylopus_pyriformis', 'CA', 'PY', 'CAPY', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (26, 'Campylopus_species', 'CA', 'SP', 'CASP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (27, 'Cardamine_flexuosa', 'CA', 'FL', 'CAFL', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (28, 'Carex_bigelowii', 'CA', 'BI', 'CABI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (29, 'Carex_curta', 'CA', 'CU', 'CACU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (30, 'Carex_echinata', 'CA', 'EC', 'CAEC', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (31, 'Carex_flacca', 'CA', 'FL', 'CAFL', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (32, 'Carex_nigra', 'CA', 'NI', 'CANI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (33, 'Carex_panicea', 'CA', 'PA', 'CAPA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (34, 'Carex_rostrata', 'CA', 'RO', 'CARO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (35, 'Carex_species', 'CA', 'SP', 'CASP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (36, 'Cerastium_fontanum', 'CE', 'FO', 'CEFO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (37, 'Chamerion_angustifolium', 'CH', 'AN', 'CHAN', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (38, 'Cladonia_arbuscula', 'CL', 'AR', 'CLAR', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (39, 'Cladonia_coccifera', 'CL', 'CO', 'CLCO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (40, 'Cladonia_crustose', 'CL', 'CR', 'CLCR', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (41, 'Cladonia_floerkeana', 'CL', 'FL', 'CLFL', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (42, 'Cladonia_incrassata', 'CL', 'IN', 'CLIN', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (43, 'Cladonia_portentosa', 'CL', 'PO', 'CLPO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (44, 'Cladonia_pyxidata', 'CL', 'PY', 'CLPY', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (45, 'Cladonia_rangiforms', 'CL', 'RA', 'CLRA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (46, 'Cladonia_species', 'CL', 'SP', 'CLSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (47, 'Cladonia_species_crustose', 'CL', 'SP', 'CLSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (48, 'Cladonia_uncialis', 'CL', 'UN', 'CLUN', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (49, 'Crataegus_monogyna', 'CR', 'MO', 'CRMO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (50, 'Dactylorhiza_fuschii', 'DA', 'FU', 'DAFU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (51, 'Deschampsia_cespitosa', 'DE', 'CE', 'DECE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (52, 'Deschampsia_flexuosa', 'DE', 'FL', 'DEFL', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (53, 'Dicranella_heteromalla', 'DI', 'HE', 'DIHE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (54, 'Dicranella_species', 'DI', 'SP', 'DISP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (55, 'Dicranum_majus', 'DI', 'MA', 'DIMA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (56, 'Dicranum_scoparium', 'DI', 'SC', 'DISC', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (57, 'Diplophyllum_albicans', 'DI', 'AL', 'DIAL', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (58, 'Drosera_anglica', 'DR', 'AN', 'DRAN', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (59, 'Drosera_rotundifolia', 'DR', 'RO', 'DRRO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (60, 'Dryopteris_carthusiana', 'DR', 'CA', 'DRCA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (61, 'Dryopteris_dilatata', 'DR', 'DI', 'DRDI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (62, 'Dryopteris_felix_mas', 'DR', 'FE', 'DRFE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (63, 'Dryopteris_species', 'DR', 'SP', 'DRSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (64, 'Empetrum_nigrum', 'EM', 'NI', 'EMNI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (65, 'Epilobium_lanceolatum', 'EP', 'LA', 'EPLA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (66, 'Epilobium_montanum', 'EP', 'MO', 'EPMO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (67, 'Epilobium_species', 'EP', 'SP', 'EPSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (68, 'Equisetum_arvense', 'EQ', 'AR', 'EQAR', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (69, 'Equisetum_palustre', 'EQ', 'PA', 'EQPA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (70, 'Erica_cinerea', 'ER', 'CI', 'ERCI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (71, 'Erica_tetralix', 'ER', 'TE', 'ERTE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (72, 'Eriophorum_angustifolium', 'ER', 'AN', 'ERAN', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (73, 'Eriophorum_vaginatum', 'ER', 'VA', 'ERVA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (74, 'Eurhynchium_praelongum', 'EU', 'PR', 'EUPR', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (75, 'Festuca_ovina', 'FE', 'OV', 'FEOV', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (76, 'Fruticose_lichen', 'FR', 'LI', 'FRLI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (77, 'Fruticose_lichen_white', 'FR', 'LI', 'FRLI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (78, 'Fumaria_capreolata', 'FU', 'CA', 'FUCA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (79, 'Galium_saxatile', 'GA', 'SA', 'GASA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (80, 'Glyceria_species', 'GL', 'SP', 'GLSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (81, 'Holcus_lanatus', 'HO', 'LA', 'HOLA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (82, 'Huperzia_selago', 'HU', 'SE', 'HUSE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (83, 'Hylocomium_splendens', 'HY', 'SP', 'HYSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (84, 'Hypnum_cupressiforme', 'HY', 'CU', 'HYCU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (85, 'Hypnum_jutlandicum', 'HY', 'JU', 'HYJU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (86, 'Ilex_aquifolium_sapling', 'IL', 'AQ', 'ILAQ', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (87, 'Juncus_acutiflorus', 'JU', 'AC', 'JUAC', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (88, 'Juncus_articulatus', 'JU', 'AR', 'JUAR', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (89, 'Juncus_bufonius', 'JU', 'BU', 'JUBU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (90, 'Juncus_bulbosus', 'JU', 'BU', 'JUBU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (91, 'Juncus_effusus', 'JU', 'EF', 'JUEF', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (92, 'Juncus_inflexus', 'JU', 'IN', 'JUIN', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (93, 'Juncus_squarrosus', 'JU', 'SQ', 'JUSQ', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (94, 'Kindbergia_praelonga', 'KI', 'PR', 'KIPR', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (95, 'Leucobryum_glaucum', 'LE', 'GL', 'LEGL', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (96, 'Lichen', 'LI', NULL, 'LICH', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (97, 'Liverwort', 'LI', NULL, 'LIVE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (98, 'Lophocolea_bidentata', 'LO', 'BI', 'LOBI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (99, 'Luzula_campestris', 'LU', 'CA', 'LUCA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (100, 'Luzula_multiflora', 'LU', 'MU', 'LUMU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (101, 'Luzula_pilosa', 'LU', 'PI', 'LUPI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (102, 'Luzula_species', 'LU', 'SP', 'LUSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (103, 'Mnium_hornum', 'MN', 'HO', 'MNHO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (104, 'Molinia_caerulea', 'MO', 'CA', 'MOCA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (105, 'Mylia_anomala', 'MY', 'AN', 'MYAN', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (106, 'Mylia_taylorii', 'MY', 'TA', 'MYTA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (107, 'Myrica_gale', 'MY', 'GA', 'MYGA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (108, 'Nardus_stricta', 'NA', 'ST', 'NAST', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (109, 'Narthecium_ossifragum', 'NA', 'OS', 'NAOS', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (110, 'Neottia_cordata', 'NE', 'CO', 'NECO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (111, 'Odontoschisma_sphagni', 'OD', 'SP', 'ODSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (112, 'Oxalis_acetosella', 'OX', 'AC', 'OXAC', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (113, 'Parmelia_species', 'PA', 'SP', 'PASP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (114, 'Pedicularis_species', 'PE', 'SP', 'PESP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (115, 'Pedicularis_sylvatica', 'PE', 'SY', 'PESY', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (116, 'Peltigera_species', 'PE', 'SP', 'PESP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (117, 'Persicaria_maculosa', 'PE', 'MA', 'PEMA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (118, 'Philonotis_fontana', 'PH', 'FO', 'PHFO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (119, 'Picea_sitchensis', 'PI', 'SI', 'PISI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (120, 'Picea_sitchensis_canopy', 'PI', 'SI', 'PISI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (121, 'Picea_sitchensis_sapling', 'PI', 'SI', 'PISI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (122, 'Picea_sitchensis_seedling', 'PI', 'SI', 'PISI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (123, 'Picea_species', 'PI', 'SP', 'PISP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (124, 'Picea_species_canopy', 'PI', 'SP', 'PISP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (125, 'Pinguicula_species', 'PI', 'SP', 'PISP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (126, 'Pinguicula_vulgaris', 'PI', 'VU', 'PIVU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (127, 'Pinus_species', 'PI', 'SP', 'PISP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (128, 'Pinus_species_seedling', 'PI', 'SP', 'PISP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (129, 'Pinus_sylvestris', 'PI', 'SY', 'PISY', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (130, 'Pinus_sylvestris_seedling', 'PI', 'SY', 'PISY', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (131, 'Plagiothecium_species', 'PL', 'SP', 'PLSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (132, 'Plagiothecium_undulatum', 'PL', 'UN', 'PLUN', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (133, 'Pleurozia_purpurea', 'PL', 'PU', 'PLPU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (134, 'Pleurozium_schreberi', 'PL', 'SC', 'PLSC', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (135, 'Poa_annua', 'PO', 'AN', 'POAN', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (136, 'Poa_trivialis', 'PO', 'TR', 'POTR', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (137, 'Polygala_serpyllifolia', 'PO', 'SE', 'POSE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (138, 'Polygala_species', 'PO', 'SP', 'POSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (139, 'Polygonum_aviculare', 'PO', 'AV', 'POAV', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (140, 'Polytrichum_commune', 'PO', 'CO', 'POCO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (141, 'Polytrichum_formosum', 'PO', 'FO', 'POFO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (142, 'Polytrichum_juniperinum', 'PO', 'JU', 'POJU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (143, 'Polytrichum_species', 'PO', 'SP', 'POSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (144, 'Polytrichum_strictum', 'PO', 'ST', 'POST', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (145, 'Potentilla_erecta', 'PO', 'ER', 'POER', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (146, 'Pseudoscleropodium_purum', 'PS', 'PU', 'PSPU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (147, 'Pteridium_aquilinum', 'PT', 'AQ', 'PTAQ', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (148, 'Ptilidium_ciliare', 'PT', 'CI', 'PTCI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (149, 'Quercus_petraea', 'QU', 'PE', 'QUPE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (150, 'Racomitrium_lanuginosum', 'RA', 'LA', 'RALA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (151, 'Ranunculus_repens', 'RA', 'RE', 'RARE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (152, 'Rhynchospora_alba', 'RH', 'AL', 'RHAL', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (153, 'Rhytidiadelphus_loreus', 'RH', 'LO', 'RHLO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (154, 'Rhytidiadelphus_species', 'RH', 'SP', 'RHSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (155, 'Rhytidiadelphus_squarrosus', 'RH', 'SQ', 'RHSQ', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (156, 'Rhytidiadelphus_triquetrus', 'RH', 'TR', 'RHTR', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (157, 'Rosa_canina', 'RO', 'CA', 'ROCA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (158, 'Rubus_chamaemorus', 'RU', 'CH', 'RUCH', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (159, 'Rubus_fruticosus', 'RU', 'FR', 'RUFR', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (160, 'Rubus_idaeus', 'RU', 'ID', 'RUID', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (161, 'Rumex_obtusifolius', 'RU', 'OB', 'RUOB', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (162, 'Salix_cinerea_seedling', 'SA', 'CI', 'SACI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (163, 'Scapania_nemorea', 'SC', 'NE', 'SCNE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (164, 'Sorbus_aucuparia', 'SO', 'AU', 'SOAU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (165, 'Sorbus_aucuparia_seedling', 'SO', 'AU', 'SOAU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (166, 'Sphagnum_auriculatum', 'SP', 'AU', 'SPAU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (167, 'Sphagnum_capillifolium', 'SP', 'CA', 'SPCA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (168, 'Sphagnum_capillifolium_subsp_capillifolium', 'SP', 'CA', 'SPCA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (169, 'Sphagnum_capillifolium_subsp_rubellum', 'SP', 'CA', 'SPCA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (170, 'Sphagnum_compactum', 'SP', 'CO', 'SPCO', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (171, 'Sphagnum_cuspidatum', 'SP', 'CU', 'SPCU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (172, 'Sphagnum_denticulatum', 'SP', 'DE', 'SPDE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (173, 'Sphagnum_fallax', 'SP', 'FA', 'SPFA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (174, 'Sphagnum_fimbriatum', 'SP', 'FI', 'SPFI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (175, 'Sphagnum_fuscum', 'SP', 'FU', 'SPFU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (176, 'Sphagnum_magellanicum', 'SP', 'MA', 'SPMA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (177, 'Sphagnum_majus', 'SP', 'MA', 'SPMA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (178, 'Sphagnum_palustre', 'SP', 'PA', 'SPPA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (179, 'Sphagnum_papillosum', 'SP', 'PA', 'SPPA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (180, 'Sphagnum_pulchrum', 'SP', 'PU', 'SPPU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (181, 'Sphagnum_recurvum', 'SP', 'RE', 'SPRE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (182, 'Sphagnum_rubellum', 'SP', 'RU', 'SPRU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (183, 'Sphagnum_species', 'SP', 'SP', 'SPSP', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (184, 'Sphagnum_squarrosum', 'SP', 'SQ', 'SPSQ', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (185, 'Sphagnum_squarrosum_papillosum', 'SP', 'SQ', 'SPSQ', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (186, 'Sphagnum_subnitens', 'SP', 'SU', 'SPSU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (187, 'Sphagnum_subsecundum', 'SP', 'SU', 'SPSU', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (188, 'Sphagnum_tenellum', 'SP', 'TE', 'SPTE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (189, 'Stellaria_alsine', 'ST', 'AL', 'STAL', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (190, 'Thuidium_tamariscinum', 'TH', 'TA', 'THTA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (191, 'Trichophorum_cespitosum', 'TR', 'CE', 'TRCE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (192, 'Trichophorum_germanicum', 'TR', 'GE', 'TRGE', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (193, 'Triglochin_palustre', 'TR', 'PA', 'TRPA', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (194, 'Vaccinium_microcarpum', 'VA', 'MI', 'VAMI', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (195, 'Vaccinium_myrtillus', 'VA', 'MY', 'VAMY', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (196, 'Vaccinium_oxycoccos', 'VA', 'OX', 'VAOX', NULL);
INSERT INTO "public"."lu_vegetation_species" ("fid" , "veg_sp", "genus", "specific", "key", "dict") VALUES (197, 'Vaccinium_vitis_idaea', 'VA', 'VI', 'VAVI', NULL);
COMMIT;
BEGIN;
CREATE TABLE "public"."lu_dung" (    "fid" SERIAL,    CONSTRAINT "lu_dung_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."lu_dung" ADD COLUMN "dung" VARCHAR(20);
INSERT INTO "public"."lu_dung" ("fid" , "dung") VALUES (1, 'rabbit');
INSERT INTO "public"."lu_dung" ("fid" , "dung") VALUES (2, 'mountain hare');
INSERT INTO "public"."lu_dung" ("fid" , "dung") VALUES (3, 'sheep');
INSERT INTO "public"."lu_dung" ("fid" , "dung") VALUES (4, 'cattle');
INSERT INTO "public"."lu_dung" ("fid" , "dung") VALUES (5, 'deer');
COMMIT;
BEGIN;
CREATE TABLE "public"."lu_browsing" (    "fid" SERIAL,    CONSTRAINT "lu_browsing_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."lu_browsing" ADD COLUMN "browsing" VARCHAR(20);
INSERT INTO "public"."lu_browsing" ("fid" , "browsing") VALUES (1, 'Light');
INSERT INTO "public"."lu_browsing" ("fid" , "browsing") VALUES (2, 'Moderate');
INSERT INTO "public"."lu_browsing" ("fid" , "browsing") VALUES (3, 'Heavy');
COMMIT;
BEGIN;
CREATE TABLE "public"."lu_aspect" (    "fid" SERIAL,    CONSTRAINT "lu_aspect_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."lu_aspect" ADD COLUMN "aspect" VARCHAR(10);
INSERT INTO "public"."lu_aspect" ("fid" , "aspect") VALUES (1, 'N');
INSERT INTO "public"."lu_aspect" ("fid" , "aspect") VALUES (2, 'NE');
INSERT INTO "public"."lu_aspect" ("fid" , "aspect") VALUES (3, 'E');
INSERT INTO "public"."lu_aspect" ("fid" , "aspect") VALUES (4, 'SE');
INSERT INTO "public"."lu_aspect" ("fid" , "aspect") VALUES (5, 'S');
INSERT INTO "public"."lu_aspect" ("fid" , "aspect") VALUES (6, 'SW');
INSERT INTO "public"."lu_aspect" ("fid" , "aspect") VALUES (7, 'W');
INSERT INTO "public"."lu_aspect" ("fid" , "aspect") VALUES (8, 'NW');
COMMIT;
BEGIN;
CREATE TABLE "public"."protocol_c_vegetation" (    "fid" SERIAL,    CONSTRAINT "protocol_c_vegetation_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "plot_id" VARCHAR(20);
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "name" VARCHAR(50);
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "percentage_coverage" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "quadrat_id_fk" VARCHAR(10);
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_1" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_2" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_3" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_4" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_5" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_6" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_7" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_8" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_9" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_10" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_11" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_12" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_13" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_14" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_15" INTEGER;
ALTER TABLE "public"."protocol_c_vegetation" ADD COLUMN "cell_16" INTEGER;
COMMIT;
BEGIN;
CREATE TABLE "public"."protocol_d_peat_humification " (    "fid" SERIAL,    CONSTRAINT "protocol_d_peat_humification _pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."protocol_d_peat_humification " ADD COLUMN "scale" VARCHAR(10);
ALTER TABLE "public"."protocol_d_peat_humification " ADD COLUMN "comments" VARCHAR(200);
ALTER TABLE "public"."protocol_d_peat_humification " ADD COLUMN "quadrat_id_fk" VARCHAR(10);
ALTER TABLE "public"."protocol_d_peat_humification " ADD COLUMN "plot_id" VARCHAR(10);
COMMIT;
BEGIN;
CREATE TABLE "public"."protocol_e_photography" (    "fid" SERIAL,    CONSTRAINT "protocol_e_photography_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."protocol_e_photography" ADD COLUMN "date" timestamp with time zone;
ALTER TABLE "public"."protocol_e_photography" ADD COLUMN "surveyor_initials" VARCHAR(10);
ALTER TABLE "public"."protocol_e_photography" ADD COLUMN "bearing" INTEGER;
ALTER TABLE "public"."protocol_e_photography" ADD COLUMN "photo_reference" VARCHAR(200);
ALTER TABLE "public"."protocol_e_photography" ADD COLUMN "quadrat_id_fk" VARCHAR(10);
ALTER TABLE "public"."protocol_e_photography" ADD COLUMN "comments" VARCHAR(200);
ALTER TABLE "public"."protocol_e_photography" ADD COLUMN "photo" VARCHAR(200);
ALTER TABLE "public"."protocol_e_photography" ADD COLUMN "plot_id" VARCHAR(10);
COMMIT;
BEGIN;
CREATE TABLE "public"."protocol_c_trampling" (    "fid" SERIAL,    CONSTRAINT "protocol_c_trampling_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "plot_id" VARCHAR(10);
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "quadrat_id_fk" VARCHAR(10);
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_1" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_2" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_3" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_4" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_5" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_6" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_7" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_8" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_9" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_10" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_11" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_12" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_13" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_14" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_15" INTEGER;
ALTER TABLE "public"."protocol_c_trampling" ADD COLUMN "cell_16" INTEGER;
COMMIT;
BEGIN;
CREATE TABLE "public"."protocol_c_height" (    "fid" SERIAL,    CONSTRAINT "protocol_c_height_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_1" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_2" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_3" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_4" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_5" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_6" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_7" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_8" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_9" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_10" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_11" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_12" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_13" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_14" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_15" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "cell_16" INTEGER;
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "plot_id" VARCHAR(10);
ALTER TABLE "public"."protocol_c_height" ADD COLUMN "quadrat_id_fk" VARCHAR(10);
COMMIT;
BEGIN;
CREATE TABLE "public"."protocol_b_reprofiling" (    "fid" SERIAL,    CONSTRAINT "protocol_b_reprofiling_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "plot_id" VARCHAR(10);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "type" VARCHAR(10);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "reprofiled_area_intact" VARCHAR(5);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "turfs_slipped" VARCHAR(5);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "turfs_fallen_flipped" VARCHAR(5);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "turfs_dieback" VARCHAR(5);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "ongoing_erosion" VARCHAR(5);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "water_erosion" VARCHAR(5);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "trampling_erosion" VARCHAR(5);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "trampling_species" VARCHAR(50);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "vegetation_colonisation" VARCHAR(5);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "angle_reprofiled_sides" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_bare_peat" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "id" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "quadrat_id_fk" VARCHAR(20);
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_heather" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_other_dwarf_shrubs" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_purple_moor_grass" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_other_grasses" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_hare_tail_cottongrass" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_common_cottongrass" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_deergrass" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_all_rushes" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_sphagnum_sp" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_other_bryophytes" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_lichen_species" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_trees_and_shrubs" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_bare_rock" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_open_water" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_mineral_soil" INTEGER;
ALTER TABLE "public"."protocol_b_reprofiling" ADD COLUMN "coverage_mulch_debris" INTEGER;
COMMIT;
BEGIN;
CREATE TABLE "public"."protocol_b_unbloking" (    "fid" SERIAL,    CONSTRAINT "protocol_b_unbloking_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "plot_id" VARCHAR(10);
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "type" VARCHAR(50);
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "active_water_flow" VARCHAR(5);
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "water_flow_speed" VARCHAR(10);
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_bare_peat" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_open_water" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "id" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "quadrat_id_fk" VARCHAR(20);
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_heather" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_dwarf_shrubs" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_purple_moor_grass" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_other_grasses" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_hares_tail_cottongrass" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_common_cottongrass" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_deergrass" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_all_rushes" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_sphagnum" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_other_bryophytes" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_lichen_sp" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_trees_shrubs" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_bare_rock" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_mineral_soil" INTEGER;
ALTER TABLE "public"."protocol_b_unbloking" ADD COLUMN "coverage_mulch_debris" INTEGER;
COMMIT;
BEGIN;
CREATE TABLE "public"."protocol_b_blocking" (    "fid" SERIAL,    CONSTRAINT "protocol_b_blocking_pk" PRIMARY KEY ("fid") );
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "plot_id" VARCHAR(10);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "id" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "type" VARCHAR(20);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "blocking_feature_intact" VARCHAR(5);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "erosion_under_blocking" VARCHAR(5);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "trampling" VARCHAR(5);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "trampling_species" VARCHAR(200);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "water_retained" VARCHAR(5);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "water_depth" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "sediments" VARCHAR(5);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "veg_on_blocking" VARCHAR(5);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "veg_on_pool" VARCHAR(5);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "veg_pool_bog_species" VARCHAR(200);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_discernible" VARCHAR(5);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_veg_colonisation" VARCHAR(5);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_size" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_bare_peat" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_open_water" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "quadrat_id_fk" VARCHAR(20);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_heather" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_other_dwarf_shrubs" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_purple_moor_grass" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_other_grasses" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_hares_trail_cottongrass" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_common_cottongrass" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_deergrass" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_all_rushes" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_sphagum_sp" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_other_bryophytes" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_lichen" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_trees_and_shrubs" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_bare_rock" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_mineral_soil" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "pit_cover_mulch_debris" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "water_active_flow" VARCHAR(5);
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "water_distributed_across_surface" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_bare_peat" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_bare_rock" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_open_water" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_heather" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_other_dwarf_shrubs" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_purple_moor_grass" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_other_grasses" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_hares_tail" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_common_cottongrass" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_deergrass" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_all_rushes" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_sphagnum_sp" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_other_bryophytes" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_lichen_sp" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_trees_shrubs" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_mineral" INTEGER;
ALTER TABLE "public"."protocol_b_blocking" ADD COLUMN "bbf_cover_mulch" INTEGER;
SELECT setval(pg_get_serial_sequence('"public"."cell_05_05_meters"', 'fid'), MAX("fid")) FROM "public"."cell_05_05_meters";
SELECT setval(pg_get_serial_sequence('"public"."lu_land_management"', 'fid'), MAX("fid")) FROM "public"."lu_land_management";
SELECT setval(pg_get_serial_sequence('"public"."lu_pre_restoration_condition_cat"', 'fid'), MAX("fid")) FROM "public"."lu_pre_restoration_condition_cat";
SELECT setval(pg_get_serial_sequence('"public"."lu_vegetation_species"', 'fid'), MAX("fid")) FROM "public"."lu_vegetation_species";
SELECT setval(pg_get_serial_sequence('"public"."lu_dung"', 'fid'), MAX("fid")) FROM "public"."lu_dung";
SELECT setval(pg_get_serial_sequence('"public"."lu_browsing"', 'fid'), MAX("fid")) FROM "public"."lu_browsing";
SELECT setval(pg_get_serial_sequence('"public"."lu_aspect"', 'fid'), MAX("fid")) FROM "public"."lu_aspect";
COMMIT;
